image: docker:27

services:
  - docker:27-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: jahangiraze/shopery

stages:
  - docker

docker-build-push:
  stage: docker
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
