server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL:true}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

feign:
  client:
    config:
      backoffice-ms:
        url: ${BACKOFFICE_MS}
      filenet-ms:
        url: ${FILENET_MS}
      payment-ms:
        url: ${PAYMENT_MS}
      order-ms:
        url: ${ORDER_MS}
      blog-ms:
        url: ${BLOG_MS}
      ai-ms:
        url: ${AI_MS}
