spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopery_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - display-name: LOCAL API Documentation
