spring:
  application:
    name: shopery

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      timeout: 2000ms

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expiration: ${ACCESS_TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION}

resilience4j:
  ratelimiter:
    instances:
      auth-rate-limiter:
        limitForPeriod: 5
        limitRefreshPeriod: 120s
        timeoutDuration: 100ms

topic:
  notification: notification-topic
