spring:
  application:
    name: shopery
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopery_db}
    username: ${DB_USERNAME:shopery_user}
    password: ${DB_PASSWORD:shopery_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${NO_REPLY_BREVO_USERNAME}
    password: ${NO_REPLY_BREVO_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    from: ${NO_REPLY_SHOPERY_USERNAME}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expiration: ${ACCESS_TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION}
  frontend:
    base-url: ${FRONTEND_BASE_URL}

server:
  port: ${PORT:8080}

aws:
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}

claude:
  api:
    key: ${CLAUDE_API_KEY}
    url: https://api.anthropic.com/v1/messages
    model: claude-sonnet-4-20250514
    max-tokens: 1024
    version: 2023-06-01

resilience4j:
  ratelimiter:
    instances:
      auth-rate-limiter:
        limitForPeriod: 5
        limitRefreshPeriod: 120s
        timeoutDuration: 100ms
